version: '3.7'

services:
  api:
    build:
      context: .
      target: builder
    command: ["sh", "-c", "realize start --run"]
    ports:
      - "8080:8080"
    environment:
      APP_ENV: "develop"
      GO111MODULE: "on"
      PORT: 8080
    volumes:
      - ".:/go/app"
    networks:
      api:

networks:
  api:

volumes:
  log:
